### ISSUE TITLE
Add-on breaks with Kodi 19, due to the Python 3 interpreter

### ISSUE THREAD

**Issue by gdomenici** [gdomenici/plugin.video.pcloud-video-streaming#21]
pcloud-video-streaming cannot start on Kodi 19 preview (Kodi 19.0-ALPHA1) due to the Python 3 interpreter present in that Kodi version instead of Python 2 in all previous versions. See https://www.ghacks.net/2019/11/19/kodi-19-may-break-some-add-ons/.

See also https://kodi.tv/article/attention-addon-developers-migration-python-3.

The error in the log is:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ModuleNotFoundError'>
                                            Error Contents: No module named 'urllib2'
                                            Traceback (most recent call last):
                                              File "C:\Users\Guido\AppData\Roaming\Kodi\addons\plugin.video.pcloud-video-streaming\addon.py", line 1, in <module>
                                                import resources.lib.pcloudapi
                                              File "C:\Users\Guido\AppData\Roaming\Kodi\addons\plugin.video.pcloud-video-streaming\resources\lib\pcloudapi.py", line 2, in <module>
                                                import urllib2
                                            ModuleNotFoundError: No module named 'urllib2'
```

**Comment by gdomenici** [comment]
Still to do: also make it work on Python 2, for all Kodi versions <=18.
