### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by spacebug96** [gdomenici/plugin.video.pcloud-video-streaming#45]
I use CoreELEC 19.3-Matrix with latest pcloud-video-streaming plugin, but I got following error,  for non empty folders:
> 2021-12-07 23:20:06.851 T:6026    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'ConnectionResetError'>
>                                                    Error Contents: [Errno 104] Connection reset by peer
>                                                    Traceback (most recent call last):
>                                                      File "/storage/.kodi/addons/plugin.video.pcloud-video-streaming/addon.py", line 121, in <module>
>                                                        folderContents = pcloud.ListFolderContents(folderID, isMyShares)
>                                                      File "/storage/.kodi/addons/plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py", line 137, in ListFolderContents
>                                                        response = self.ExecuteRequest(url)
>                                                      File "/storage/.kodi/addons/plugin.video.pcloud-video-streaming/resources/lib/pcloudapi.py", line 89, in ExecuteRequest
>                                                        response = self.HttpHandler.open(httpRequest)
>                                                      File "/usr/lib/python3.8/urllib/request.py", line 525, in open
>                                                      File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
>                                                      File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
>                                                      File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
>                                                      File "/usr/lib/python3.8/urllib/request.py", line 1358, in do_open
>                                                      File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
>                                                      File "/usr/lib/python3.8/http/client.py", line 316, in begin
>                                                      File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
>                                                      File "/usr/lib/python3.8/socket.py", line 669, in readinto
>                                                      File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
>                                                      File "/usr/lib/python3.8/ssl.py", line 1099, in read
>                                                    ConnectionResetError: [Errno 104] Connection reset by peer
>                                                    -->End of Python script error report<--

Do you have any idea why this error is coming? Please help me to solve it

**Comment by gdomenici** [comment]
Hi @spacebug96 
Thanks for reporting this issue, and for the log. I'm afraid I cannot reproduce this, not easily at least... Do you see this each and every time you try and access a non-empty folder? Or only sometimes? Does the folder in question have any "peculiar" characteristics? (maybe an unusually large number of files?)

Also, what is the exact version of the plugin you're on?

Kind regards,

Guido

**Comment by spacebug96** [comment]
Hello @gdomenici,

Yes, I see this problem ever time when I switch to folder with files. Folder which contains sub-folders only is displayed correctly. 
The problem doesn't depends on number of files. 

I use latest version for matrix, so 1.5.1


Best regards,
spacebug

**Comment by gdomenici** [comment]
Hey @spacebug96 

I have to admit I have never tested the plugin on CoreElec (only Windows, Mac, Android, and LibreElec on Raspberry PI), But I can give it a shot.

Here on the [CoreElec download page](https://coreelec.org/#download) I see there is a number of hardware options to pick from. Probably makes sense for me to create/find a virtual machine of the same hardware you're using.

What hardware are you running CoreElec on?

Kind regards,

Guido

**Comment by spacebug96** [comment]
Dear @gdomenici,

I use X96 Max box with following CPU:
model name      : Amlogic S905X2 rev b
Hardware        : Amlogic
Revision        : 0400

I think the LE image is general for all boxes, only the DTB is different. For my HW is "sm1_s905x3_4g_1gbit" 

If you want, I can help to debug the problem with MITM reverse proxy. I'm a developer also :)

Best regards,
spacebug
